.TH dh_qmldeps 1 "2014-11-29" "Debian helper for qml dependencies"
.SH NAME
.B dh_qmldeps
.SH LINK
.P
The documentation can be found online: https://qt-kde-team.pages.debian.net/dh_qmldeps.html
.SH LICENSE
.P
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.SH AUTHORS
Sandro Knauß <hefee@debian.org>
