#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2023 Sandro Knauß <hefee@debian.org>
# SPDX-License-Identifier: LGPL-2.0-or-later

"""
Gives a list of Debian qml packages that are needed as dependency.
This script should become a dh_helper script.

The needed qml packages need to be installed on the system, otherwise the
dependency is not detected and you will see:

Missing QML module XXX

The arguments are the arguments for qmlimportscanner.

Sample execution:

pkgkde-getqmldepends --qt 5 -- -qrcFiles PATHTO/itinerary-23.04.2/src/app/qml.qrc
"""

import sys
import pathlib

sys.path.insert(0,'/usr/share/pkg-kde-tools')
parent = str(pathlib.Path(__file__).parent.absolute())
if parent not in ("/usr/bin", "/bin"):
    sys.path.insert(0,parent)

from pythonlib import qmldeps

if __name__ == '__main__':
    qmldeps.main()
